'use client';

import React, { useState } from 'react';
import {
  FileText,
  Sparkles,
  RefreshCw,
  Printer,
  Download,
  Calendar,
  ShieldCheck,
  Activity,
  AlertTriangle,
  ArrowRightLeft,
  CheckCircle2,
  Cpu,
} from 'lucide-react';
import { useDashboard } from '../../context/DashboardContext';

export const DailyIntelligenceReportView: React.FC = () => {
  const { dailyReport, refreshDailyReport } = useDashboard();
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleRefresh = async () => {
    setIsRefreshing(true);
    await refreshDailyReport();
    setTimeout(() => setIsRefreshing(false), 600);
  };

  const handleExportMarkdown = () => {
    const content = `# ${dailyReport.headline}\n\n**Date**: ${dailyReport.date}\n**Generated By**: ${dailyReport.model_used}\n**Generated At**: ${dailyReport.generated_at}\n\n## Key Metrics\n- Total Emergency Cases: ${dailyReport.key_metrics.total_cases}\n- High-Acuity Critical Cases: ${dailyReport.key_metrics.critical_cases}\n- Jurisdiction SLA Compliance: ${dailyReport.key_metrics.sla_compliance_pct}%\n- Autonomous Tier 1 Auto-Reroutes: ${dailyReport.key_metrics.auto_reroutes}\n\n${dailyReport.summary_markdown}\n`;
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `LifeLine_AI_Daily_Intelligence_Report_${dailyReport.date}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="bg-white dark:bg-[#0e1424] rounded-3xl p-6 sm:p-8 border border-slate-200 dark:border-slate-800 shadow-sm space-y-6">
      {/* Header & AI Model Attribution */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 dark:border-slate-800/80 pb-5">
        <div className="flex items-start gap-3.5">
          <div className="w-12 h-12 rounded-2xl bg-indigo-50 dark:bg-indigo-600/20 border border-indigo-200 dark:border-indigo-500/30 text-indigo-700 dark:text-indigo-400 flex items-center justify-center font-black shrink-0">
            <Sparkles className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-black uppercase tracking-wider bg-indigo-100 dark:bg-indigo-500/20 text-indigo-800 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-400/30 px-2.5 py-0.5 rounded-full flex items-center gap-1 font-mono">
                <Sparkles className="w-3 h-3 text-indigo-600 dark:text-indigo-400" />
                <span>AI EXECUTIVE BRIEFING</span>
              </span>
              <span className="text-xs font-mono font-bold bg-slate-100 dark:bg-[#111728] text-slate-700 dark:text-slate-300 px-2.5 py-0.5 rounded-full border border-slate-200 dark:border-slate-700">
                Model: {dailyReport.model_used}
              </span>
            </div>
            <h2 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white mt-1">
              {dailyReport.headline}
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 font-mono mt-0.5">
              Synthesis of regional dispatch volume, hospital strain, and autonomous reroute decisions.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2.5 font-mono text-xs">
          <button
            onClick={handleRefresh}
            disabled={isRefreshing}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 border border-slate-200 dark:border-slate-700 transition-colors font-bold shadow-sm"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isRefreshing ? 'animate-spin' : ''}`} />
            <span>{isRefreshing ? 'Regenerating...' : 'Regenerate'}</span>
          </button>

          <button
            onClick={handleExportMarkdown}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold transition-all shadow-md shadow-indigo-600/30"
          >
            <Download className="w-3.5 h-3.5" />
            <span>{copied ? 'Downloaded!' : 'Export Markdown'}</span>
          </button>
        </div>
      </div>

      {/* Key Metrics Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono">
        <div className="p-4 rounded-2xl bg-slate-50 dark:bg-[#111728] border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] text-slate-500 dark:text-slate-400 block uppercase">Total Dispatches</span>
          <span className="text-2xl font-black text-slate-900 dark:text-white">{dailyReport.key_metrics.total_cases}</span>
          <span className="text-[10px] text-sky-700 dark:text-sky-400 block mt-0.5">Autonomous Routing</span>
        </div>

        <div className="p-4 rounded-2xl bg-slate-50 dark:bg-[#111728] border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] text-slate-500 dark:text-slate-400 block uppercase">Critical (NEWS2 ≥ 7)</span>
          <span className="text-2xl font-black text-red-600 dark:text-red-400">{dailyReport.key_metrics.critical_cases}</span>
          <span className="text-[10px] text-red-600 dark:text-red-400 block mt-0.5">Level-1 Trauma Bays</span>
        </div>

        <div className="p-4 rounded-2xl bg-slate-50 dark:bg-[#111728] border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] text-slate-500 dark:text-slate-400 block uppercase">SLA Compliance</span>
          <span className="text-2xl font-black text-emerald-700 dark:text-emerald-400">{dailyReport.key_metrics.sla_compliance_pct}%</span>
          <span className="text-[10px] text-emerald-700 dark:text-emerald-400 block mt-0.5">&lt; 15s Target Met</span>
        </div>

        <div className="p-4 rounded-2xl bg-slate-50 dark:bg-[#111728] border border-slate-200 dark:border-slate-800 shadow-sm">
          <span className="text-[10px] text-slate-500 dark:text-slate-400 block uppercase">Auto-Reroutes</span>
          <span className="text-2xl font-black text-purple-700 dark:text-purple-400">{dailyReport.key_metrics.auto_reroutes}</span>
          <span className="text-[10px] text-purple-700 dark:text-purple-400 block mt-0.5">Diversion Bypasses</span>
        </div>
      </div>

      {/* Markdown Content Panel */}
      <div className="p-6 rounded-2xl bg-slate-50 dark:bg-[#111728] border border-slate-200 dark:border-slate-800 text-slate-800 dark:text-slate-200 text-xs leading-relaxed space-y-4 font-sans shadow-sm">
        <div className="whitespace-pre-wrap font-sans text-xs sm:text-sm text-slate-800 dark:text-slate-300 leading-relaxed">
          {dailyReport.summary_markdown}
        </div>
      </div>
    </div>
  );
};
